---
iosv-1:
  hostname: '192.168.178.64'
  port: 22
  username: 'admin'
  password: 'cisco'
  platform: 'cisco_ios'
iosv-2:
  hostname: '192.168.178.65'
  port: 22
  username: 'admin'
  password: 'cisco'
  platform: 'cisco_ios'